version: 1.0
jobs:
  build:
    docker:
      - image: cimg/android:2025.01

        steps:
          - checkout

            # project environment setup
          - run: chmod +x project_setup.sh
          - run:
              name: Setting Up Project Environment
              command: ./project_setup.sh

          # run gradle build
          - run: chmod +x gradlew
          - run:
              name: Android Gradle Build
              command: ./gradlew clean assemble bundle --stacktrace

          # store build files
          - store_artifacts:
              path: app/build/outputs/apk
          - store_artifacts:
              path: app/build/outputs/bundle