version: 2.1
jobs:
  build:
    docker:
      - image: cimg/android:2025.01
    steps:
      - checkout

      # Project setup
      - run: chmod +x project_setup.sh
      - run:
          name: Setting Up Project Environment
          command: ./project_setup.sh

      # Gradle build
      - run: chmod +x gradlew
      - run:
          name: Android Gradle Build
          command: ./gradlew clean assembleRelease bundleRelease --stacktrace

      # Store APK and AAB artifacts
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk
          destination: release-apk
      - store_artifacts:
          path: app/build/outputs/bundle/release/app-release.aab
          destination: release-bundle
